/*
 * Web interpreter bridge: exposes ucode as a WebAssembly module callable
 * from JavaScript. Replaces the native CLI's main().
 *
 * Public API (exported to JS via emscripten):
 *
 *   ucode_run(source)        run source as a ucode script
 *   ucode_eval(source)       run source as an expression, print result
 *   ucode_run_file(path)     run a file from the virtual filesystem
 *   ucode_render_file(path, template_mode)  run a file with its output
 *                            diverted to the render buffer (see below)
 *   ucode_reset()            drop the VM (globals, closures) and start fresh
 *   ucode_module_count()     number of statically linked modules
 *   ucode_version()          pointer to a NUL-terminated C string with the
 *                            ucode version the wasm was built from
 *                            (abbreviated commit + build date, baked in at
 *                            compile time via the UCODE_VERSION macro)
 *   ucode_get_output()       pointer to a NUL-terminated C string with all
 *                            output captured since the last call (stdout
 *                            only; C's stderr is captured separately in
 *                            Module.stderrText, see web-bridge.js);
 *                            empty string if none
 *   ucode_get_render()       likewise for the render buffer
 *   ucode_get_error()        pointer to a NUL-terminated C string with the
 *                            last compile/run error, or empty string
 *
 * Module preloading
 * -----------------
 * The statically linked modules (see web-bridge-modules.inc) are
 * registered in the global `modules` dictionary at VM init, and their
 * names are listed in the parse config's force_dynlink_list. The
 * compiler therefore emits a runtime lookup for `import ... from "math"`
 * (and friends) instead of a file search, and uc_require_path() checks
 * the `modules` dictionary before the search path, so require() of the
 * same names resolves to the preloaded objects. There is no dlopen under
 * wasm; this is the whole module-resolution story.
 *
 * Virtual filesystem (see "Project filesystem" below)
 * ---------------------------------------------------
 *
 *   ucode_vfs_write(path, data, len)  create/overwrite a file (len < 0 -> strlen)
 *   ucode_vfs_read(path)              file contents ("" if unreadable)
 *   ucode_vfs_remove(path)            unlink / rmdir
 *   ucode_vfs_clear(root)             recursive delete of a tree
 *   ucode_vfs_list(root)              JSON listing of a tree
 *
 * Output capture
 * --------------
 * Rather than relying on emscripten's TTY/stdout (which is unreliable for
 * C printf output after the module's initial run in MODULARIZE mode), all
 * ucode output is written to a growable C buffer owned by this bridge.
 * The ucode VM's `print()` and error reporting write to `vm->output`
 * (a FILE*). We point that at a memfd-free custom FILE* backed by
 * printbuf, and expose the buffer contents to JS after each run.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <time.h>
#include <errno.h>

#if defined(__EMSCRIPTEN__)
#include <emscripten.h>
#endif

#include <ucode/compiler.h>
#include <ucode/lib.h>
#include <ucode/source.h>
#include <ucode/types.h>
#include <ucode/vm.h>
#include <ucode/internal/util.h>

/* Auto-generated by build.sh: declares web_module_entry_t, WEB_MODULES_TABLE,
 * and the per-module entry wrapper functions. */
#include "web-bridge-modules.inc"

static const web_module_entry_t web_modules[] = {
	WEB_MODULES_TABLE
};

/* ------------------------------------------------------------------ */
/* Output capture                                                      */
/*                                                                     */
/* ucode's print() writes to `vm->output` (a FILE*). We point that at   */
/* an open_memstream()-backed FILE* whose contents live in a plain C   */
/* buffer. After each run we copy that buffer into out_buf and expose   */
/* it to JS. This sidesteps emscripten's TTY/stdout entirely, which is  */
/* unreliable for C-level writes after the module's initial run.       */
/*                                                                     */
/* There are two independent capture streams:                          */
/*   console - what print()/errors produce during a normal run         */
/*   render  - what a template run produces; vm->output is temporarily  */
/*             diverted here so that a template's output can be handed   */
/*             to JS separately from the log (a template that itself    */
/*             calls print() still ends up in the rendered document,    */
/*             exactly like `ucode -T` on the command line).            */
/* ------------------------------------------------------------------ */

typedef struct {
	char *mem;
	size_t sz;
	FILE *file;
	struct printbuf *buf;
} capture_t;

static capture_t cap_console = { NULL, 0, NULL, NULL };
static capture_t cap_render = { NULL, 0, NULL, NULL };

/* Backwards-compatible aliases for the console stream. */
#define captured_file cap_console.file

static void
capture_init(capture_t *cap)
{
	if (cap->file)
		return;

	cap->buf = printbuf_new();
	cap->file = open_memstream(&cap->mem, &cap->sz);
}

/* Copy whatever ucode wrote into the memstream into the printbuf and reset
 * the memstream so the next run starts fresh. */
static void
capture_collect(capture_t *cap)
{
	if (!cap->file || !cap->buf)
		return;

	fflush(cap->file);

	if (cap->sz > 0 && cap->mem) {
		printbuf_memappend(cap->buf, cap->mem, (int)cap->sz);
		/* Reset the memstream: seek back to 0 so subsequent writes
		 * overwrite the same region and cap->sz restarts. */
		rewind(cap->file);
		cap->sz = 0;
	}
}

static void
capture_clear(capture_t *cap)
{
	if (cap->buf) {
		cap->buf->bpos = 0;
		cap->buf->buf[0] = '\0';
	}
}

/* Materialise a capture stream into a NUL-terminated, growable static
 * buffer suitable for handing to JS's UTF8ToString(). */
static char *
capture_string(capture_t *cap, char **bufp, size_t *capp)
{
	size_t len = cap->buf ? (size_t)cap->buf->bpos : 0;

	if (len + 1 > *capp) {
		*capp = len + 4096;
		*bufp = realloc(*bufp, *capp);
	}

	if (*bufp == NULL) {
		*capp = 0;
		return (char *)"";
	}

	if (len > 0)
		memcpy(*bufp, cap->buf->buf, len);

	(*bufp)[len] = '\0';

	return *bufp;
}

static char *out_str = NULL;
static size_t out_str_cap = 0;
static char *render_str = NULL;
static size_t render_str_cap = 0;

/* ------------------------------------------------------------------ */
/* Module preloading                                                   */
/* ------------------------------------------------------------------ */

/*
 * Register the statically linked modules in the global `modules`
 * dictionary. uc_require_path() consults that dictionary before the
 * search path, so require()/import of these names resolve to the
 * preloaded objects without any .so lookup (there is no dlopen under
 * wasm). The same names are listed in force_dynlink_list (see
 * vm_init()), so the compiler emits a runtime lookup for them instead
 * of trying to resolve a file.
 */
static void
preload_modules(uc_vm_t *vm)
{
	uc_value_t *scope = uc_vm_scope_get(vm);
	uc_value_t *modtable = ucv_property_get(scope, "modules");
	size_t i;

	for (i = 0; i < sizeof(web_modules) / sizeof(web_modules[0]); i++) {
		uc_value_t *obj = ucv_object_new(vm);

		web_modules[i].init(vm, obj);
		ucv_object_add(modtable, web_modules[i].name, obj);
	}
}

/* ------------------------------------------------------------------ */
/* VM lifecycle                                                        */
/* ------------------------------------------------------------------ */

static uc_vm_t vm = { 0 };
static bool vm_inited = false;
static char last_error[4096] = { 0 };

/* Persistent parse config. Kept static (not stack-local) because
 * uc_vm_init() stores a *pointer* to it in vm->config and the compiler
 * reads vm->config on every uc_compile() -- a stack-local would dangle
 * after vm_ensure() returns. raw_mode + the /pen + /virtual search paths
 * make compile-time `import` of the pen's own .uc modules work in the
 * REPL. */
static uc_parse_config_t vm_config;

static void
vm_init(void)
{
	size_t i;

	memset(&vm_config, 0, sizeof(vm_config));
	vm_config.raw_mode = true;
	/* Build the module search path from scratch (NOT uc_search_path_init, which
	 * copies the build-time LIB_SEARCH_PATH default -- a single colon-joined
	 * string the compile-time import resolver does not split on ':'), one entry
	 * at a time.
	 *
	 * The statically linked modules (fs, math, io, ...) are deliberately not
	 * on the search path: they are preloaded into the global `modules`
	 * dictionary below, and uc_require_path() checks that cache before the
	 * search path, so require()/import resolve them directly.
	 *
	 *   /pen/          the pen's own files, so require("lib") and
	 *                  import { x } from "lib" resolve to /pen/lib.uc
	 *   /virtual/      source modules seeded into MEMFS (demos, examples)
	 *
	 * (Both entries are globs matching *.uc.) The global REQUIRE_SEARCH_PATH
	 * array is a copy of this list (vm.c builds it in
	 * uc_vm_alloc_global_scope), so scripts can still shuffle it at runtime. */
	vm_config.module_search_path.count = 0;
	vm_config.module_search_path.entries = NULL;
	uc_search_path_add(&vm_config.module_search_path, (char *)"/pen/*.uc");
	uc_search_path_add(&vm_config.module_search_path, (char *)"/virtual/*.uc");

	/* Force the preloaded module names to be treated as dynamic-link modules
	 * at compile time, so `import { x } from "math"` compiles to a runtime
	 * lookup of the preloaded object instead of a file search. */
	for (i = 0; i < sizeof(web_modules) / sizeof(web_modules[0]); i++)
		uc_vector_push(&vm_config.force_dynlink_list,
		               xstrdup(web_modules[i].name));

	vm.gc_interval = 1000;
	uc_vm_init(&vm, &vm_config);
	uc_stdlib_load(uc_vm_scope_get(&vm));
	preload_modules(&vm);

	/* Redirect ucode's output (vm->output) to our memstream capture. */
	capture_init(&cap_console);
	capture_init(&cap_render);
	if (cap_console.file)
		vm.output = cap_console.file;

	vm_inited = true;
}

static void
vm_ensure(void)
{
	if (!vm_inited)
		vm_init();
}

/*
 * Flush ucode's output after a command.
 *
 * No VM state to clean here: uc_vm_execute() leaves the value stack and
 * the pending exception in a clean state for completed runs (it clears a
 * pending exception on entry and unwinds the callframes on exit), and the
 * global scope -- with the user's variables -- is deliberately left
 * alone, which is what makes the REPL stateful.
 */
static void
vm_cleanup(void)
{
	if (!vm_inited)
		return;

	/* Deliver partial lines stuck in emscripten's TTY buffers before the JS
	 * side reads the capture: the TTYs only emit on newline, so a write
	 * without a trailing newline (warn("progress")) would otherwise sit in
	 * the buffer and leak into the next run. */
	fflush(stdout);
	fflush(stderr);
}

/*
 * Destroy the current VM and start a new one. The virtual filesystem is
 * untouched (only the interpreter state -- globals, closures, loaded
 * modules -- is dropped), which is what a "run this pen from scratch"
 * button needs: reproducible runs without re-uploading the files.
 */
EMSCRIPTEN_KEEPALIVE
void
ucode_reset(void)
{
	/* Flush text stuck in the TTY buffers (the previous run's unfinished
	 * line) so it lands in the capture about to be cleared -- a re-run must
	 * not inherit it. The JS side clears Module.stderrText right after. */
	fflush(stdout);
	fflush(stderr);

	if (vm_inited) {
		uc_vm_free(&vm);
		memset(&vm, 0, sizeof(vm));
		vm_inited = false;
	}

	vm_init();

	capture_clear(&cap_console);
	capture_clear(&cap_render);

	last_error[0] = '\0';
}

/* ------------------------------------------------------------------ */
/* Run helpers                                                         */
/* ------------------------------------------------------------------ */

/*
 * Compile `source` under the given mode. Template mode is a property of the
 * source file, not of the VM, so the flags are flipped on the (static,
 * VM-referenced) parse config just for the duration of the compile and
 * restored afterwards -- uc_compile() hands the config to the lexer, which
 * must not outlive the call.
 */
static uc_program_t *
compile_source(uc_source_t *src, bool template_mode, char **errp)
{
	bool raw = vm_config.raw_mode, ls = vm_config.lstrip_blocks, tb = vm_config.trim_blocks;
	uc_program_t *prog;

	if (template_mode) {
		vm_config.raw_mode = false;
		vm_config.lstrip_blocks = true;
		vm_config.trim_blocks = true;
	}

	prog = uc_compile(vm.config, src, errp);

	vm_config.raw_mode = raw;
	vm_config.lstrip_blocks = ls;
	vm_config.trim_blocks = tb;

	return prog;
}

/*
 * Run `source` (NUL-terminated) as a program.
 *
 * `name` is used as the source name so that diagnostics -- and, more
 * importantly, the runpath used to resolve relative include()/import()
 * -- point at the pen file rather than at "[-e]".
 *
 * uc_source_new_buffer() takes ownership of the buffer it is handed and
 * free()s it when the source object is released (types.c), so the buffer
 * passed to it must be heap memory owned by ucode. Callers hand us
 * pointers into wasm memory that JS owns (and frees), so copy first.
 */
static void
run_source_named(const char *name, const char *source, bool is_expr, bool template_mode)
{
	uc_source_t *src;
	uc_program_t *prog;
	char *err = NULL, *copy;
	uc_value_t *res = NULL;
	uc_vm_status_t status;

	last_error[0] = '\0';

	copy = strdup(source ? source : "\n");

	if (!copy) {
		snprintf(last_error, sizeof(last_error), "out of memory");
		return;
	}

	src = uc_source_new_buffer(name, copy, strlen(copy));

	if (!src) {
		free(copy);
		snprintf(last_error, sizeof(last_error), "failed to create source buffer");
		return;
	}

	prog = compile_source(src, template_mode, &err);
	uc_source_put(src);

	if (!prog) {
		snprintf(last_error, sizeof(last_error), "%s", err ? err : "compile error");
		free(err);
		return;
	}

	status = uc_vm_execute(&vm, prog, &res);

	switch (status) {
	case STATUS_OK:
		if (is_expr && res) {
			FILE *out = vm.output ? vm.output : stdout;

			if (ucv_type(res) == UC_STRING) {
				fwrite(ucv_string_get(res), ucv_string_length(res), 1, out);
				fputc('\n', out);
			} else {
				uc_stringbuf_t *pb = xprintbuf_new();

				ucv_to_stringbuf_formatted(&vm, pb, res, 0, '\t', 1);
				fwrite(pb->buf, pb->bpos, 1, out);
				fputc('\n', out);
				printbuf_free(pb);
			}
		}
		break;

	case STATUS_EXIT:
		break;

	case STATUS_BREAK:
		break;

	case ERROR_COMPILE:
	case ERROR_RUNTIME:
		{
			uc_value_t *exobj = uc_vm_exception_object(&vm);

			if (exobj) {
				uc_stringbuf_t *pb = xprintbuf_new();

				ucv_to_stringbuf_formatted(&vm, pb, exobj, 0, '\t', 1);
				snprintf(last_error, sizeof(last_error), "%s", pb->buf);
				printbuf_free(pb);
				ucv_put(exobj);
			}
		}
		break;
	}

	if (res)
		ucv_put(res);

	uc_program_put(prog);
}

static void
run_source(const char *source, bool is_expr)
{
	run_source_named("[-e]", source, is_expr, false);
}

/* Read a whole file into a freshly malloc'd NUL-terminated buffer, or
 * NULL. Caller frees. */
static char *
file_read_owned(const char *path, size_t *lenp)
{
	static const size_t chunk = 65536;
	char *buf = NULL, *tmp;
	size_t len = 0, n;
	FILE *f;

	f = fopen(path, "rb");

	if (!f)
		return NULL;

	while ((len % chunk) == 0 || len == 0) {
		tmp = realloc(buf, len + chunk);

		if (!tmp)
			break;

		buf = tmp;
		n = fread(buf + len, 1, chunk - (len % chunk), f);
		len += n;

		if (n == 0)
			break;
	}

	fclose(f);

	if (!buf)
		return NULL;

	buf[len] = '\0';

	if (lenp)
		*lenp = len;

	return buf;
}

/* ------------------------------------------------------------------ */
/* Exported API                                                        */
/*                                                                     */
/* All string parameters are passed as pointers into wasm memory that  */
/* the caller filled via stringToUTF8(). This avoids relying on        */
/* emscripten's automatic JS->C string conversion, which is unreliable  */
/* when the function is invoked after the module's initial run in      */
/* MODULARIZE mode.                                                    */
/* ------------------------------------------------------------------ */

EMSCRIPTEN_KEEPALIVE
void ucode_run(char *source)
{
	vm_ensure();
	capture_collect(&cap_console);
	run_source(source, false);
	capture_collect(&cap_console);
	vm_cleanup();
}

EMSCRIPTEN_KEEPALIVE
void ucode_eval(char *source)
{
	vm_ensure();
	capture_collect(&cap_console);
	run_source(source, true);
	capture_collect(&cap_console);
	vm_cleanup();
}

/* Run a file from the virtual filesystem as a ucode script. The source name
 * is the path, so relative include()/import() inside the file resolve
 * against the file's own directory. */
EMSCRIPTEN_KEEPALIVE
void
ucode_run_file(char *path)
{
	char *content;

	vm_ensure();
	capture_collect(&cap_console);

	content = file_read_owned(path, NULL);

	if (!content) {
		snprintf(last_error, sizeof(last_error), "Cannot read '%s'", path);
		return;
	}

	run_source_named(path, content, false, false);
	free(content);

	capture_collect(&cap_console);
	vm_cleanup();
}

/*
 * Run a file with vm->output diverted to the render stream.
 *
 * With template_mode != 0 the file is compiled in ucode's template mode
 * (equivalent to `ucode -T file`), so literal text is emitted and
 * {{ expressions }} / {% statements %} are evaluated. Read the result with
 * ucode_get_render(); anything the template itself prints lands in the same
 * stream, which is what makes the rendered document complete.
 */
EMSCRIPTEN_KEEPALIVE
void
ucode_render_file(char *path, int template_mode)
{
	char *content;

	vm_ensure();
	capture_collect(&cap_console);
	capture_collect(&cap_render);

	content = file_read_owned(path, NULL);

	if (!content) {
		snprintf(last_error, sizeof(last_error), "Cannot read '%s'", path);
		return;
	}

	{
		FILE *prev = vm.output;

		if (cap_render.file)
			vm.output = cap_render.file;

		run_source_named(path, content, false, template_mode != 0);

		vm.output = prev;
	}

	free(content);

	capture_collect(&cap_render);
	vm_cleanup();
}

/* Same as ucode_render_file() but for a source string held in wasm memory. */
EMSCRIPTEN_KEEPALIVE
void
ucode_render_string(char *source, int template_mode)
{
	vm_ensure();
	capture_collect(&cap_console);
	capture_collect(&cap_render);

	{
		FILE *prev = vm.output;

		if (cap_render.file)
			vm.output = cap_render.file;

		run_source_named("[render]", source, false, template_mode != 0);

		vm.output = prev;
	}

	capture_collect(&cap_render);
	vm_cleanup();
}

/* Return a pointer into a growable static buffer containing all captured
 * console output (stdout from ucode's print()). The buffer is owned by the
 * bridge; the JS side reads it with UTF8ToString and then calls
 * ucode_clear_output. */
EMSCRIPTEN_KEEPALIVE
char *
ucode_get_output(void)
{
	capture_collect(&cap_console);

	return capture_string(&cap_console, &out_str, &out_str_cap);
}

/* Likewise for the render stream (see ucode_render_file). */
EMSCRIPTEN_KEEPALIVE
char *
ucode_get_render(void)
{
	capture_collect(&cap_render);

	return capture_string(&cap_render, &render_str, &render_str_cap);
}

EMSCRIPTEN_KEEPALIVE
void
ucode_clear_output(void)
{
	capture_clear(&cap_console);
}

EMSCRIPTEN_KEEPALIVE
void
ucode_clear_render(void)
{
	capture_clear(&cap_render);
}

EMSCRIPTEN_KEEPALIVE
const char *
ucode_get_error(void)
{
	return last_error;
}

EMSCRIPTEN_KEEPALIVE
int ucode_module_count(void)
{
	return (int)(sizeof(web_modules) / sizeof(web_modules[0]));
}

#ifndef UCODE_VERSION
#define UCODE_VERSION "unknown"
#endif

EMSCRIPTEN_KEEPALIVE
const char *
ucode_version(void)
{
	return UCODE_VERSION;
}

/* ------------------------------------------------------------------ */
/* Demo filesystem                                                     */
/*                                                                     */
/* The demo tree (demo/ in the repo) is embedded into the bridge as a   */
/* list of {path, data} entries and seeded into Emscripten's MEMFS so  */
/* the fs module has something real to read, list, and stat.           */
/*                                                                     */
/*   ucode_fs_seed_demo()   (re)create the /demo tree in MEMFS         */
/*   ucode_fs_run(path)     read a file from MEMFS and run it as ucode */
/*   ucode_fs_read(path)    return a pointer to a file's contents      */
/*   ucode_fs_list()        return a pointer to a listing of /demo     */
/* ------------------------------------------------------------------ */

#include <sys/stat.h>
#include <dirent.h>
#include <unistd.h>

/* Auto-generated by build.sh: DEMO_FILES = { {"path", "..."}, ... } */
#include "web-bridge-demo.inc"

/* Ensure a parent directory exists (mkdir -p style). */
static void
fs_mkdir_p(const char *path)
{
	char tmp[512];
	char *p;
	size_t len = strlen(path);

	if (len >= sizeof(tmp))
		return;
	memcpy(tmp, path, len + 1);

	for (p = tmp + 1; *p; p++) {
		if (*p == '/') {
			*p = '\0';
			mkdir(tmp, 0755); /* EEXIST is fine */
			*p = '/';
		}
	}
}

/* Write one file, creating parent dirs as needed. Returns 0 on success. */
static int
fs_write_embedded(const char *path, const char *data)
{
	FILE *f;

	fs_mkdir_p(path);

	f = fopen(path, "wb");
	if (!f)
		return -1;
	fwrite(data, 1, strlen(data), f);
	fclose(f);
	return 0;
}

EMSCRIPTEN_KEEPALIVE
int
ucode_fs_seed_demo(void)
{
	int i, ok = 0;

	for (i = 0; i < (int)(sizeof(DEMO_FILES) / sizeof(DEMO_FILES[0])); i++) {
		if (fs_write_embedded(DEMO_FILES[i].path, DEMO_FILES[i].data) == 0)
			ok++;
	}

	return ok;
}

/* Read a file from MEMFS into a growable static buffer; returns pointer (""
 * if the file can't be read). The buffer is owned by the bridge. */
static char *read_buf = NULL;
static size_t read_buf_cap = 0;

EMSCRIPTEN_KEEPALIVE
char *
ucode_fs_read(char *path)
{
	char *content;
	size_t len;

	content = file_read_owned(path, &len);

	if (!content)
		return (char *)"";

	if (len + 1 > read_buf_cap) {
		read_buf_cap = len + 4096;
		read_buf = realloc(read_buf, read_buf_cap);
	}

	if (!read_buf) {
		free(content);
		read_buf_cap = 0;
		return (char *)"";
	}

	memcpy(read_buf, content, len + 1);
	free(content);

	return read_buf;
}

/* Read a file from MEMFS and execute it as a ucode program. */
EMSCRIPTEN_KEEPALIVE
void
ucode_fs_run(char *path)
{
	ucode_run_file(path);
}

/* Build a listing of the /demo tree into a static buffer. Returns a
 * pointer to the NUL-terminated text. */
static char list_buf[8192];

EMSCRIPTEN_KEEPALIVE
char *
ucode_fs_list(void)
{
	struct dirent *de;
	DIR *d;
	char line[600];
	char dirpath[512];
	size_t pos = 0;

	list_buf[0] = '\0';

	#define APPEND(fmt, ...) \
		do { \
			int n = snprintf(line, sizeof(line), fmt, ##__VA_ARGS__); \
			if (n > 0 && pos + (size_t)n + 1 < sizeof(list_buf)) { \
				memcpy(list_buf + pos, line, n); \
				pos += n; \
				list_buf[pos] = '\0'; \
			} \
		} while (0)

	APPEND("/demo\n");

	d = opendir("/demo");
	if (!d)
		return list_buf;

	while ((de = readdir(d)) != NULL) {
		if (!strcmp(de->d_name, ".") || !strcmp(de->d_name, ".."))
			continue;

		snprintf(dirpath, sizeof(dirpath), "/demo/%s", de->d_name);
		if (de->d_type == DT_DIR)
			APPEND("  %s/\n", de->d_name);
		else
			APPEND("  %s\n", de->d_name);
	}
	closedir(d);

	return list_buf;
}

/* ------------------------------------------------------------------ */
/* Project filesystem                                                  */
/*                                                                     */
/* The same MEMFS tree, but driven from JS instead of being embedded at
 * build time: a pen's editor buffers are mirrored into /pen/ before each
 * run, so ucode's fs module, include(), import and render() all see the
 * files exactly as they appear in the editor.                            */
/*                                                                     */
/*   ucode_vfs_write(path, data, len)  create/overwrite (len < 0 = strlen) */
/*   ucode_vfs_read(path)              contents, "" if unreadable      */
/*   ucode_vfs_remove(path)            unlink, or rmdir for a directory */
/*   ucode_vfs_clear(root)             recursive delete of a tree      */
/*   ucode_vfs_list(root)              JSON array of {path,type,size}  */
/* ------------------------------------------------------------------ */

EMSCRIPTEN_KEEPALIVE
int
ucode_vfs_write(char *path, char *data, int len)
{
	FILE *f;
	size_t n;

	if (!path || !*path || !data)
		return -1;

	if (len < 0)
		len = (int)strlen(data);

	fs_mkdir_p(path);

	f = fopen(path, "wb");

	if (!f)
		return -1;

	n = fwrite(data, 1, (size_t)len, f);
	fclose(f);

	return n == (size_t)len ? 0 : -1;
}

EMSCRIPTEN_KEEPALIVE
int
ucode_vfs_remove(char *path)
{
	if (!path || !*path)
		return -1;

	if (unlink(path) == 0)
		return 0;

	return rmdir(path) == 0 ? 0 : -1;
}

/* Recursive delete. Depth-limited so a symlink loop (not that MEMFS has
 * any) cannot wedge the interpreter. */
static int
vfs_rm_r(const char *path, int depth)
{
	struct dirent *de;
	char child[512];
	DIR *d;
	int rv = 0;

	if (depth > 16)
		return -1;

	d = opendir(path);

	if (d) {
		while ((de = readdir(d)) != NULL) {
			if (!strcmp(de->d_name, ".") || !strcmp(de->d_name, ".."))
				continue;

			snprintf(child, sizeof(child), "%s/%s", path, de->d_name);

			if (de->d_type == DT_DIR)
				vfs_rm_r(child, depth + 1);
			else if (unlink(child) != 0)
				rv = -1;
		}

		closedir(d);

		return rmdir(path) == 0 ? rv : -1;
	}

	return unlink(path) == 0 ? 0 : -1;
}

EMSCRIPTEN_KEEPALIVE
int
ucode_vfs_clear(char *root)
{
	if (!root || !*root || !strcmp(root, "/"))
		return -1;

	return vfs_rm_r(root, 0);
}

/* JSON listing of a tree, for the file tree view and for debugging. */
static char *vfs_json = NULL;
static size_t vfs_json_cap = 0;
static size_t vfs_json_len = 0;

static void
vfs_json_reset(void)
{
	vfs_json_len = 0;

	if (vfs_json)
		vfs_json[0] = '\0';
}

static void
vfs_json_append(const char *fmt, ...)
{
	char line[1024];
	va_list ap;
	int n;

	va_start(ap, fmt);
	n = vsnprintf(line, sizeof(line), fmt, ap);
	va_end(ap);

	if (n <= 0)
		return;

	if (vfs_json_len + (size_t)n + 1 > vfs_json_cap) {
		vfs_json_cap = vfs_json_len + (size_t)n + 4096;
		vfs_json = realloc(vfs_json, vfs_json_cap);

		if (!vfs_json) {
			vfs_json_cap = 0;
			vfs_json_len = 0;
			return;
		}
	}

	memcpy(vfs_json + vfs_json_len, line, n + 1);
	vfs_json_len += (size_t)n;
}

/* JSON-escape a path into a caller supplied buffer. */
static void
json_escape(const char *s, char *out, size_t outsz)
{
	size_t o = 0;

	for (; *s && o + 7 < outsz; s++) {
		switch (*s) {
		case '\\': out[o++] = '\\'; out[o++] = '\\'; break;
		case '\"': out[o++] = '\\'; out[o++] = '\"'; break;
		case '\n': out[o++] = '\\'; out[o++] = 'n'; break;
		case '\t': out[o++] = '\\'; out[o++] = 't'; break;
		case '\r': out[o++] = '\\'; out[o++] = 'r'; break;
		default:
			if ((unsigned char)*s < 0x20)
				o += (size_t)sprintf(out + o, "u%04x", (unsigned char)*s);
			else
				out[o++] = *s;
		}
	}

	out[o] = '\0';
}

static void
vfs_walk(const char *path, int depth, int *first)
{
	struct dirent *de;
	struct stat st;
	char child[512], esc[1200];
	char **names = NULL;
	size_t count = 0, i, j;
	DIR *d;

	if (depth > 16)
		return;

	d = opendir(path);

	if (!d) {
		if (stat(path, &st) == 0) {
			json_escape(path, esc, sizeof(esc));
			vfs_json_append("%s{\"path\":\"%s\",\"type\":\"file\",\"size\":%ld}",
			                *first ? "" : ",", esc, (long)st.st_size);
			*first = 0;
		}

		return;
	}

	while ((de = readdir(d)) != NULL) {
		if (!strcmp(de->d_name, ".") || !strcmp(de->d_name, ".."))
			continue;

		names = realloc(names, (count + 1) * sizeof(*names));
		names[count++] = strdup(de->d_name);
	}

	closedir(d);

	/* sort, so the listing is stable across runs */
	for (i = 1; i < count; i++) {
		for (j = i; j > 0 && strcmp(names[j - 1], names[j]) > 0; j--) {
			char *tmp = names[j - 1];

			names[j - 1] = names[j];
			names[j] = tmp;
		}
	}

	for (i = 0; i < count; i++) {
		snprintf(child, sizeof(child), "%s/%s", path, names[i]);
		vfs_walk(child, depth + 1, first);
		free(names[i]);
	}

	free(names);
}

EMSCRIPTEN_KEEPALIVE
char *
ucode_vfs_list(char *root)
{
	int first = 1;

	vfs_json_reset();
	vfs_json_append("[");

	if (root && *root)
		vfs_walk(root, 0, &first);

	vfs_json_append("]");

	if (!vfs_json)
		return (char *)"[]";

	return vfs_json;
}
